# Use a Windows-compatible Python base image
FROM python:3.12-windowsservercore-ltsc2022

# Add project source
WORKDIR /musicbot
COPY . ./
COPY ./config sample_config


# Step 1: Download the required dependencies for WinGet installation
RUN powershell -Command " \
    Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile C:\\VCLibs.appx; \
    Invoke-WebRequest -Uri https://aka.ms/Microsoft.UI.Xaml.2.7.appx -OutFile C:\\XAML.appx; \
    Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile C:\\WinGet.msixbundle"

# Step 2: Use DISM to install the dependencies system-wide
RUN powershell -Command " \
    dism.exe /Online /Add-Package /PackagePath:C:\\VCLibs.appx; \
    dism.exe /Online /Add-Package /PackagePath:C:\\XAML.appx; \
    dism.exe /Online /Add-Package /PackagePath:C:\\WinGet.msixbundle; \
    Remove-Item C:\\VCLibs.appx, C:\\XAML.appx, C:\\WinGet.msixbundle"

# Use WinGet to install FFmpeg
RUN powershell -Command "winget install -e --id Gyan.FFmpeg -h"

# Use WinGet to install Git
RUN powershell -Command "winget install -e --id Git.Git -h"

# Verify installations
RUN powershell -Command " \
    ffmpeg -version; \
    git --version;"

# Install pip dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Create volumes for audio cache, config, data and logs
VOLUME ["/musicbot/audio_cache", "/musicbot/config", "/musicbot/data", "/musicbot/logs", "/musicbot/media"]

ENV APP_ENV=docker

ENTRYPOINT ["run.bat"]
