# Use a Windows-compatible Python base image
FROM python:3.12-windowsservercore-ltsc2022

# Add project source
WORKDIR /musicbot
COPY . ./
COPY ./config sample_config

# Install PowerShell modules for WinGet
RUN powershell -Command " \
    Install-PackageProvider -Name NuGet -Force; \
    Install-Module -Name Microsoft.WinGet.Client -Force -Scope AllUsers;"

# Use WinGet to install FFmpeg
RUN powershell -Command "winget install -e --id Gyan.FFmpeg -h"

# Use WinGet to install Git
RUN powershell -Command "winget install -e --id Git.Git -h"

# Verify installations
RUN powershell -Command " \
    ffmpeg -version; \
    git --version;"

# Install pip dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Create volumes for audio cache, config, data and logs
VOLUME ["/musicbot/audio_cache", "/musicbot/config", "/musicbot/data", "/musicbot/logs", "/musicbot/media"]

ENV APP_ENV=docker

ENTRYPOINT ["run.bat"]
