name: Test Installers

on: 
  push:
    branches:
      - test-auto-install
  pull_request:
    branches:
      - test-auto-install

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: 
          - ubuntu-latest
          - ubuntu-slim
          - ubuntu-22.04
          #- ubuntu-slim
          - macos-latest        # arm64
          - macos-14            # arm64
          #- macos-latest-large  # x64
          #- macos-14-large      # x64
          - windows-latest
          - windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run install script
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == *"windows"* ]]; then
            ./install.bat -auto
          else
            ./install.sh --auto
          fi
